# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 4241327718faa30ff3fee20d5aca7c7c66d7852fd793d8a3e2329ce1a56da311ddf16df58e32fb4a902d62d6deb2a74210870e369beeaf79d471f93c221c5165

test:
  secret_key_base: 6c7c88f55e84937dca44988a677d195309395a5a991b51b4a7ed72d61cf2d4c03627f626c0ea2dead54e45e9927c95807a963984f6bc713278261a8d9b14f99c

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
